name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Build & Test Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Install QEMU System Packages
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86 qemu-kvm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Extract Talos Version from Makefile
        id: talos-version
        run: |
          TALOS_VERSION=$(grep -E '^TALOS_VERSION \?=' Makefile | awk '{print $3}')
          echo "TALOS_VERSION=$TALOS_VERSION" >> $GITHUB_ENV
          echo "version=$TALOS_VERSION" >> $GITHUB_OUTPUT

      - name: Install talosctl
        run: |
          curl -sLo talosctl https://github.com/siderolabs/talos/releases/download/${{ steps.talos-version.outputs.version }}/talosctl-linux-amd64
          chmod +x talosctl
          sudo mv talosctl /usr/local/bin/

      - name: Run Local Test Script
        run: |
          make test-local
        env:
          CLEANUP: "true"
